Avoid NPEs on switching autocompleter views under Java 11
This is not a "real" fix; it's just defensive programming. The real cause seems
to be that when setting the new viewport view (in AutoCompleter.activateView())
the new view gets populated with the old view's items. It's not clear why this
only happens in Java 11.

Stack trace:

Uncatched exception in thread [AWT-EventQueue-0]
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at org.omegat.gui.editor.autotext.AutotextAutoCompleterView.itemToString(AutotextAutoCompleterView.java:86)
	at org.omegat.gui.editor.autocompleter.AutoCompleterListView$CellRenderer.getListCellRendererComponent(AutoCompleterListView.java:266)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.maybeUpdateLayoutState(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicListUI.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JComponent.getPreferredSize(Unknown Source)
	at java.desktop/javax.swing.JViewport.getViewSize(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI.syncScrollPaneWithViewport(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicScrollPaneUI$Handler.stateChanged(Unknown Source)
	at java.desktop/javax.swing.JViewport.fireStateChanged(Unknown Source)
	at java.desktop/javax.swing.JViewport.setView(Unknown Source)
	at java.desktop/javax.swing.JScrollPane.setViewportView(Unknown Source)
	at org.omegat.gui.editor.autocompleter.AutoCompleter.activateView(AutoCompleter.java:359)
	at org.omegat.gui.editor.autocompleter.AutoCompleter.selectNextView(AutoCompleter.java:353)
	at org.omegat.gui.editor.autocompleter.AutoCompleter.processKeys(AutoCompleter.java:188)
	at org.omegat.gui.editor.EditorTextArea3.processKeyEvent(EditorTextArea3.java:318)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.KeyboardFocusManager.redispatchEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(Unknown Source)
	at java.desktop/java.awt.DefaultKeyboardFocusManager.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

git-svn-id: svn+ssh://svn.code.sf.net/p/omegat/svn/trunk@10628 b0d8beef-cb45-0410-a8e4-c0d495c3b779